#!/bin/bash
for ((i=1;i<=300;i++)); 
do 
   cd $i
   echo $i
   jq '[.behavior.processes[].calls[].api] | unique' reports/report.json | sed 's/[^a-zA-Z0-9]//g'  >> /home/ran/.cuckoo/storage/analyses/uniq_api
   cd ..
done
