#!/bin/bash

jq '.behavior.processes[].calls[].api' reports/report.json |  sed 's/[^a-zA-Z0-9]//g' >> api_seq

for i in `cat api_seq`
do
	#echo "$i"
	catg="$(jq --arg i "$i" '.behavior.processes[].calls[] | select(.api==$i)|.category' reports/report.json | head -1 |  sed 's/[^a-zA-Z0-9]//g')" # get the category name
	#echo "$catg"
	line_no="$(awk "/$i/{ print NR; exit }" $catg)"  #get the line number
	#echo "$line_no"
        sym_catg="$(echo ${catg:0:3})"
	#echo "$sym_catg"
        fin_sym="${sym_catg}${line_no}"
	echo $fin_sym >> indexed_api_seq
done
