#!/bin/bash
INPUT=eight_fam.csv
OLDIFS=$IFS
IFS=','
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read flname dob ssn tel status
do
	echo "Name : $Family"
	
done < $INPUT
IFS=$OLDIFS
