#! /bin/bash





for d in *; do
  if [ -d "$d" ]; then
    echo "$d"
    cd $d
    for f in *
        do
        #echo $f
	    sed -i '2s/^/'"$d, "'/' $f 
	    mv $f ~/Desktop/proj/zip/all
    done
    cd ..
    
  fi
done


